people:
  # The TISS API result contains user records that are not meant to be displayed.
  # Therefore this whitelist can be used to filter the result set.
  whitelist:
    - Gertrude Kappel
    - Claudia Habersack
    - Robert Bill
    - Jürgen Cito
    - Victor Gabriel Dulca
    - Christiane Floyd
    - Thomas Grechenig
    - Christian Huemer
    - Martin Peter Krajiczek
    - Marion Murzek
    - Galina Paskaleva
    - Marion Scholz
    - Michael Schröder
    - Marek Straka
    - Bernhard Wally
