people:
  # The TISS API result contains user records that are not meant to be displayed.
  # All names must match the names used in TISS.
  # Therefore this whitelist can be used to filter the result set.
  # This whitelist will be the base of any blacklists, meaning this list is applied before the blacklists.
  whitelist:
    - Gertrude Kappel
    - Claudia Habersack
    - Robert Bill
    - Jürgen Cito
    - Victor Gabriel Dulca
    - Christiane Floyd
    - Thomas Grechenig
    - Christian Huemer
    - Martin Peter Krajiczek
    - Marion Murzek
    - Galina Paskaleva
    - Marion Scholz
    - Michael Schröder
    - Marek Straka
    - Bernhard Wally

courses:
  # If any whitelisted persons should be excluded from course fetching, list here
  blacklist:
    - Thomas Grechenig
