people:
  # Automatic profile creation:
  #   * The TISS API result contains user records that are not meant to be displayed.
  #   * This whitelist can be used to filter the result set.
  #   * The script will create a profile page IF AND ONLY IF
  #     - the person's name is on the following whitelist
  #     - the person is a member of the BIG TISS research unit
  #     - the name matches the person's name used in TISS
  # WARNING: A person's courses and publications will only be fetched if included on this whitelist.
  #          In some cases it may be necessary to whitelist people that are not members of the BIG TISS research unit
  #          in order to fetch their publications. Records like that will not have a profile page created or courses
  #          fetched, but publications will be loaded as intended.
  # This whitelist is the base of any blacklists, meaning this list is applied first.
  whitelist:
    - Gertrude Kappel
    - Claudia Habersack
    - Robert Bill
    - Jürgen Cito
    - Victor Gabriel Dulca
    - Christiane Floyd
    - Thomas Grechenig
    - Christian Huemer
    - Martin Peter Krajiczek
    - Marion Murzek
    - Galina Paskaleva
    - Marion Scholz
    - Michael Schröder
    - Marek Straka
    - Bernhard Wally

courses:
  # If a whitelisted person should be excluded from course fetching, list here
  blacklist:
    - Thomas Grechenig

publications:
  # If a whitelisted person should be excluded from publication fetching, list here
  #blacklist:
  #  - Thomas Grechenig
  blacklist: []
  # The publication database does not necessarily use the same names as TISS.
  # In order to link names with the user profiles, names must be transformed to the correct name identifier
  # Example:
  #   transform:
  #     Maximilian Mustermann: Max Mustermann
  #     M. Mustermann: Max Mustermann
  # This setup will map all names matching either "Maximilian Mustermann" or "M. Mustermann" to "Max Mustermann"
  # WARNING: ALL NAMES THAT CONTAIN NON ASCII LETTERS MUST PROVIDE TRANSFORM RECORDS REMOVING THEM
  transform:
    Marcel Straka: Marek Straka
    Gerti Kappel: Gertrude Kappel
    Jürgen Cito: Juergen Cito
    Michael Schröder: Michael Schroeder
